import { Component } from '@angular/core';
import * as i0 from "@angular/core";
export class Header {
    static ɵfac = function Header_Factory(__ngFactoryType__) { return new (__ngFactoryType__ || Header)(); };
    static ɵcmp = /*@__PURE__*/ i0.ɵɵdefineComponent({ type: Header, selectors: [["app-header"]], decls: 5, vars: 0, consts: [[1, "app-header"], [1, "brand"], ["src", "/omega_logo.png", "alt", "Omega SM", 1, "brand-logo"], [1, "brand-name"]], template: function Header_Template(rf, ctx) { if (rf & 1) {
            i0.ɵɵdomElementStart(0, "header", 0)(1, "div", 1);
            i0.ɵɵdomElement(2, "img", 2);
            i0.ɵɵdomElementStart(3, "span", 3);
            i0.ɵɵtext(4, " Omega SM ");
            i0.ɵɵdomElementEnd()()();
        } }, styles: ["[_nghost-%COMP%] {\n  display: block;\n}\n\n\n\n\n\n\n.app-header[_ngcontent-%COMP%] {\n  display: flex;\n  align-items: center;\n\n  height: 72px;\n\n  padding: 0 24px;\n\n  margin-left: 72px;\n\n  background: #ffffff;\n\n  border-bottom: 1px solid #e4e4e7;\n}\n\n\n\n\n\n\n.brand[_ngcontent-%COMP%] {\n  display: flex;\n  align-items: center;\n\n  gap: 10px;\n}\n\n\n\n\n\n\n.brand-logo[_ngcontent-%COMP%] {\n  display: block;\n\n  width: 38px;\n  height: 38px;\n\n  object-fit: contain;\n}\n\n\n\n\n\n\n.brand-name[_ngcontent-%COMP%] {\n  color: #18181b;\n\n  font-size: 1.05rem;\n  font-weight: 700;\n\n  letter-spacing: -0.025em;\n\n  white-space: nowrap;\n}\n\n\n\n\n\n\n@media (max-width: 768px) {\n\n  .app-header[_ngcontent-%COMP%] {\n    justify-content: center;\n\n    height: 64px;\n\n    margin-left: 0;\n\n    padding: 0 16px;\n  }\n\n  .brand-logo[_ngcontent-%COMP%] {\n    width: 34px;\n    height: 34px;\n  }\n\n  .brand-name[_ngcontent-%COMP%] {\n    font-size: 1rem;\n  }\n}"] });
}
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassMetadata(Header, [{
        type: Component,
        args: [{ imports: [], selector: 'app-header', template: "<header class=\"app-header\">\n\n  <div class=\"brand\">\n\n    <img\n      src=\"/omega_logo.png\"\n      alt=\"Omega SM\"\n      class=\"brand-logo\"\n    />\n\n    <span class=\"brand-name\">\n      Omega SM\n    </span>\n\n  </div>\n\n</header>", styles: [":host {\n  display: block;\n}\n\n\n/* =========================================\n   HEADER\n   ========================================= */\n\n.app-header {\n  display: flex;\n  align-items: center;\n\n  height: 72px;\n\n  padding: 0 24px;\n\n  margin-left: 72px;\n\n  background: #ffffff;\n\n  border-bottom: 1px solid #e4e4e7;\n}\n\n\n/* =========================================\n   BRAND\n   ========================================= */\n\n.brand {\n  display: flex;\n  align-items: center;\n\n  gap: 10px;\n}\n\n\n/* =========================================\n   LOGO\n   ========================================= */\n\n.brand-logo {\n  display: block;\n\n  width: 38px;\n  height: 38px;\n\n  object-fit: contain;\n}\n\n\n/* =========================================\n   NAME\n   ========================================= */\n\n.brand-name {\n  color: #18181b;\n\n  font-size: 1.05rem;\n  font-weight: 700;\n\n  letter-spacing: -0.025em;\n\n  white-space: nowrap;\n}\n\n\n/* =========================================\n   MOBILE\n   ========================================= */\n\n@media (max-width: 768px) {\n\n  .app-header {\n    justify-content: center;\n\n    height: 64px;\n\n    margin-left: 0;\n\n    padding: 0 16px;\n  }\n\n  .brand-logo {\n    width: 34px;\n    height: 34px;\n  }\n\n  .brand-name {\n    font-size: 1rem;\n  }\n}\n"] }]
    }], null, null); })();
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassDebugInfo(Header, { className: "Header", filePath: "src/app/components/header/header.ts", lineNumber: 9 }); })();
